version: '3.9'

services:
  server:
    build:
      context: server
    container_name: licsky-server
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/licsky
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - network
  front:
    build:
      context: lic-sky
    container_name: licsky-front
    ports:
      - "4200:80"
    networks:
      - network
  db:
    image: postgres
    container_name: db
#    ports:
#      - "5432:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
    environment:
      - POSTGRES_DB=licsky
      - POSTGRES_PASSWORD=postgres
volumes:
  db:
networks:
  network:

